name: ZHYW

on:
    workflow_dispatch:
    schedule:
        - cron: "*/30 0-14 * * *"
    watch:
        types: [started]

env:
  DING_TOKEN: ${{ secrets.DING_TOKEN }}
  DING_SECRET: ${{ secrets.DING_SECRET }}
  FLAGURL: ${{ secrets.FLAGURL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: requirements
      run: |
        pip3 install -r requirements.txt

    - name: Run
      run: |
        python3 main.py --client huawei --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}
